---
################################################################################
#
# Copyright 2013 Crown copyright (c)
# Land Information New Zealand and the New Zealand Government.
# All rights reserved
#
# This program is released under the terms of the new BSD license. See the
# LICENSE file for more information.
#
################################################################################

# Create database
- name: Create AIMS database
  postgresql_db:
    name: "{{ db_name }}"
    encoding: 'UTF-8'
    template: template_postgis
    owner: dba
    state: present
  become: yes
  become_user: postgres

# Create linz_dba used by roads + admin_bdy
- name: Create database superusers
  postgresql_user:
    name: "{{ item }}" # GRANT BDA privs from ansible deployment
    role_attr_flags: "NOLOGIN,SUPERUSER"
    state: present
  with_items: 
    - linz_dba
    - bde_dba
  become: yes
  become_user: postgres
